name:        mega-sdist
version:     0.3.3.2
synopsis:    Handles uploading to Hackage from mega repos
description: Please see the description on Github at <https://github.com/snoyberg/mega-sdist#readme>
category:    Distribution
author:      Michael Snoyman
maintainer:  michael@snoyman.com
license:     MIT
github:      snoyberg/mega-sdist

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >=4 && <5
- bytestring
- conduit >= 1.3
- conduit-extra
- http-conduit >= 2.3
- optparse-simple
- rio
- rio-orphans
- tar-conduit >= 0.2.1
- yaml

executables:
  mega-sdist:
    main: mega-sdist.hs
    ghc-options: -threaded -with-rtsopts=-N
