resolver: lts-12.20
extra-deps:
- git: https://github.com/commercialhaskell/stack
  commit: d32016cad63eca75f370352b4220763769c18128
  subdirs:
  - subs/pantry/
- Cabal-2.4.0.1@rev:0
- hpack-0.31.1@rev:0
- infer-license-0.2.0@rev:0 #for hpack-0.31
- tar-conduit-0.3.1@rev:0
- yaml-0.10.4.0@rev:0 #for hpack-0.31
