resolver: lts-11.0
extra-deps:
- archive: https://github.com/commercialhaskell/rio/archive/248557ef565278b3e63568d7b33a60c19652e9f1.tar.gz
  subdirs:
  - rio
  - rio-orphans
- typed-process-0.2.2.0@rev:0
- unliftio-0.2.6.0@rev:0
